name: Publish

on:
  workflow_dispatch:

jobs:
  pre_publish:
    name: Prepublish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-sbf-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-sbf-
      - name: Get nightly toolchain version
        id: nightly
        run: echo "version=$(make nightly-version)" >> $GITHUB_OUTPUT
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.nightly.outputs.version }}
          components: rustfmt, clippy
      - name: Get Trezoa version
        id: trezoa
        run: echo "version=$(make trezoa-version)" >> $GITHUB_OUTPUT
      - uses: trezoaplex-foundation/actions/install-trezoa@v1
        with:
          cache: true
          version: ${{ steps.trezoa.outputs.version }}
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - name: Prepublish
        shell: bash
        run: make prepublish

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: pre_publish
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-sbf-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-sbf-
      - name: Get Trezoa version
        id: trezoa
        run: echo "version=$(make trezoa-version)" >> $GITHUB_OUTPUT
      - uses: trezoaplex-foundation/actions/install-trezoa@v1
        with:
          cache: true
          version: ${{ steps.trezoa.outputs.version }}
      - name: Publish
        shell: bash
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          ARGS: "--locked"
        run: make publish
